name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Build APK using Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v1
      env:
        USER: root
        PIP_BREAK_SYSTEM_PACKAGES: "1"
      with:
        workdir: .
        buildozer_version: latest
        command: buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: video-downloader-apk
        path: bin/*.apk
